# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: Workflow

on: [push, pull_request]

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v1
      - name: Render Rmarkdown files
        run: |
          
          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: autocommit
        with:
          commit_message: ":construction_worker: Rendering rmd files"
  lint-project:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install lintr
        run: install.packages("lintr")
        shell: Rscript {0}
      - name: Lint root directory
        run: lintr::lint_dir()
        shell: Rscript {0}
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: autocommit
        with:
          commit_message: ":construction_worker: Linting"
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install lintr
        run: install.packages("lintr")
        shell: Rscript {0}
      - name: Lint
        run: lintr::lint_package()
        shell: Rscript {0}
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: autocommit
        with:
          commit_message: ":construction_worker: Linting 2"
  style:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install dependencies
        run: install.packages("styler")
        shell: Rscript {0}
      - name: Enable styler cache
        run: styler::cache_activate()
        shell: Rscript {0}
      - name: Determine cache location
        id: styler-location
        run: |
          cat(
            "##[set-output name=location;]",
            styler::cache_info(format = "tabular")$location,
            "\n",
            sep = ""
          )
        shell: Rscript {0}

      - name: Cache styler
        uses: actions/cache@v2
        with:
          path: ${{ steps.styler-location.outputs.location }}
          key: ${{ runner.os }}-styler-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-styler-
            ${{ runner.os }}-
      - name: Style
        run: styler::style_pkg(filetype = c(".R", ".Rmd", ".Rmarkdown", ".Rnw"))
        shell: Rscript {0}
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: autocommit
        with:
          commit_message: ":construction_worker: Code formatting"