name: Workflow
on: [push, pull_request]
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install dependencies
        run: install.packages("styler")
        shell: Rscript {0}
      - name: Enable styler cache
        run: styler::cache_activate()
        shell: Rscript {0}
      - name: Determine cache location
        id: styler-location
        run: |
          cat(
            "##[set-output name=location;]",
            styler::cache_info(format = "tabular")$location,
            "\n",
            sep = ""
          )
        shell: Rscript {0}
      - name: Cache styler
        uses: actions/cache@v2
        with:
          path: ${{ steps.styler-location.outputs.location }}
          key: ${{ runner.os }}-styler-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-styler-
            ${{ runner.os }}-
      - name: Style
        run: styler::style_dir(filetype = c(".r", ".R", ".Rmd", ".Rmarkdown", ".Rnw"))
        shell: Rscript {0}
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: autocommit
        with:
          commit_message: ":construction_worker: Code formatting"
  lint-project:
    runs-on: ubuntu-latest
    needs: [style]
    steps:
      - uses: actions/checkout@v2
      - name: Pull modifications
        run: git pull
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install lintr
        run: install.packages("lintr")
        shell: Rscript {0}
      - name: Lint root directory
        run: lintr::lint_dir()
        shell: Rscript {0}
  Tests:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: macOS-latest,   r: 'release' }
          - { os: windows-latest, r: 'release' }
          - { os: ubuntu-latest,   r: 'release' }
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      - name: Install testhat
        run: |
          install.packages("testthat")
          install.packages("stringr")
        shell: Rscript {0}
      - name: Run tests
        run: testthat::test_dir(path = "tests/testthat/")
        shell: Rscript {0}
  Render-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install Roxygen2
        run: install.packages("roxygen2")
        shell: Rscript {0}
      - name: Render doc
        run: |
          echo "Package: ${{ github.repository }} \nVersion: 1.0.0\n" > DECSRIPTION
          Rscript -e roxygen2::roxygenize()
      - name: Remove dummy file
        run: rm DECSRIPTION
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: autocommit
        with:
          commit_message: ":construction_worker: Rendering documentation."
  Render-Rmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install Rmarkdown
        run: install.packages("rmarkdown")
        shell: Rscript {0}
      - name: Render Rmarkdown files
        run: |
          RMD_PATH=($(ls src/ | grep '[.]Rmd$'))
          echo $RMD_PATH
          Rscript -e rmarkdown::render('src/plot.Rmd')
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: autocommit
        with:
          commit_message: ":construction_worker: Rendering Rmd files."
